version: '3.9'

services:
  ingestion:
    build: .
    container_name: netflix-scraper
    restart: on-failure
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
